title = "Mas Alfan"
baseurl = "https://alfan.my.id/"

# Agar front-matter pakai format YAML
MetaDataFormat = "yaml"

# untuk apply temanya
themesDir = "themes"
theme = "mastheme"

# Shortname disqus, silahkan sesuaikan
DisqusShortname = "petanikode"

# Untuk deskripsi tag meta di homepage
description = "Blog orang cakep"

# Biodata Author
[author]
    name = "Ardianta Pargo"
    homepage = "https://twitter.com/ardiantapargo"
    bio = "Pengamat Langit"
    image = "https://lh5.googleusercontent.com/-h2tLsyijw8Q/AAAAAAAAAAI/AAAAAAAACys/WBpjN_34z3o/s32-c/photo.jpg"